spring.application.name=eventos

# Conexão com o PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/eventos_db
spring.datasource.username=postgres
spring.datasource.password=victor
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurações do Hibernate/JPA
# Atualiza o banco de dados automaticamente com base nas suas classes Java
spring.jpa.hibernate.ddl-auto=update
# Mostra no console o SQL que o Spring está executando por trás dos panos
spring.jpa.show-sql=true
# Formata o SQL no console para ficar mais legível
spring.jpa.properties.hibernate.format_sql=true