spring.datasource.url=${DATABASE_URL:jdbc:postgresql://ep-round-tree-axz1xogc-pooler.c-4.us-east-2.aws.neon.tech/neondb?sslmode=require}
spring.datasource.username=${DATABASE_USERNAME:neondb_owner}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
